import type { MessageV2 } from "@/session/message-v2"

export interface Authority {
  messages: MessageV2.WithParts[]
  unavailable: boolean
}

// Child-session user turns can be generated by TaskTool. Only the topmost
// session's persisted direct user text establishes authorization for this gate.
export async function authority(input: {
  session: { id: string; parentID?: string }
  parent: (id: string) => Promise<{ id: string; parentID?: string }>
  messages: (id: string) => Promise<MessageV2.WithParts[]>
}): Promise<Authority> {
  try {
    let current = input.session
    const seen = new Set<string>()
    while (current.parentID) {
      if (seen.has(current.id) || seen.size >= 32) throw new Error("Unavailable session ancestry")
      seen.add(current.id)
      current = await input.parent(current.parentID)
    }
    if (seen.has(current.id)) throw new Error("Cyclic session ancestry")
    const messages = (await input.messages(current.id)).filter(
      (message) =>
        message.info.role === "user" &&
        message.parts.some(
          (part) => part.type === "text" && !part.synthetic && !part.ignored && part.text.trim().length > 0,
        ),
    )
    return { messages, unavailable: messages.length === 0 }
  } catch {
    return { messages: [], unavailable: true }
  }
}
